### ISSUE TITLE
convert arc to beziere

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.pathmorphing.js#1]
@dotnetCarpenter I wasnt able to find anything on how to do that when I wrote the plugin. Can you include the neccessary part from the core implementation into this one?

**Comment by dotnetCarpenter** [comment]
@Fuzzyma To be clear, you want me to find the formula for converting SVG arc properties into a bezier curve from [SVG.js](https://github.com/svgdotjs/svg.js) or you want me to write the formula for converting an SVG arc into a bezier curve?

**Comment by Fuzzyma** [comment]
I thought you wrote a plugin for path animation in which you converted all arc commands to beziere commands. But maybe I am mistaken because I cant find it in the svg.js core.

So my question: Do you know a way or do you already programed something to convert arcs to beziere curves? 

// EDIT: I am not really sure how the both possibilities you gave me differ

**Comment by dotnetCarpenter** [comment]
Unfortunately, no.

But I found these resources, if you want to give it a short.

y0 = cx+rx*cos(theta)
y0 = cy+ry*sin(theta)
both looks like bezier curves to me.

https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands

https://www.w3.org/TR/SVG/implnote.html#ArcImplementationNotes

https://www.w3.org/TR/SVG/images/paths/arcs02.svg

**Comment by Fuzzyma** [comment]
Afaik you cant replace an arc with a beziere curve. You can only approximate it with multiple curves. I already had a big implementation taken from the graphicgems implementation (c code) but it only worked with middle point of the arc and angles instead of end/start points of arcs

**Comment by Fuzzyma** [comment]
The error is: `fuse is not defined` which means that it tries to use fuse and not angolia... weired

**Comment by dotnetCarpenter** [comment]
I don't know why you want this conversion. But I'm not the right person to implement this as I don't have the know-how.
I'm closing this for now.

**Comment by Fuzzyma** [comment]
This plugin can't rely on same commands in both passes so it has to convert them to the most reliable abstraction if needed. If an arc has to be morphed into a beziere curve, I need to convert the arc to a beziere curve first.

**Comment by Fuzzyma** [comment]
@dotnetCarpenter i am sorry. I just realized that @RmiTtro did the implementation of the path morph feature. Remi may you take a look at this issue?

**Comment by RmiTtro** [comment]
Yeah, I do have a function to convert an arc to a bezier curve somewhere in my path morphing plugin. I will see if I can integrate it in this one as well. I should have time this weekend.
