### ISSUE TITLE
startOffsetNextM is not defined svg.pathmorphing.js@0.1.2/dist/svg.pathmorphing.min.js

### ISSUE THREAD

**Issue by andrespr** [svgdotjs/svg.pathmorphing.js#4]
Hello!  I'm really enjoying using SVG.js.  However, in attempting to use svg.pathmorphing.min.js using the sample code on your page, it gives the following error:

Uncaught ReferenceError: startOffsetNextM is not defined

It looks like there are two var's missing.

![image](https://user-images.githubusercontent.com/3048143/40275712-cf1f9548-5bac-11e8-8fb1-c2a9c941de80.png)

Recreation: http://studionorthern.com/dev/svg-pathmorphing-startOffsetNextM-is-not-defined/

Fix:
**var** startOffsetNextM = findNextM(startArr, startOffsetM === false ? false : startOffsetM+1)
**var** destOffsetNextM = findNextM( destArr,  destOffsetM === false ? false :  destOffsetM+1)

**Comment by Fuzzyma** [comment]
Does it fix the problem when you add the `var`? If so, can you please create a PullRequest to fix this issue? :)

**Comment by andrespr** [comment]
Hello!  Yes, it does fix the problem.  I'll create a PR tomorrow.

**Comment by andrespr** [comment]
Sorry for the delay.  PR created!

**Comment by andrespr** [comment]
[PR #5](https://github.com/svgdotjs/svg.pathmorphing.js/pull/5) merged into master.
