### ISSUE TITLE
Plugin installation instructions

### ISSUE THREAD

**Issue by mcshaman** [svgdotjs/svg.pathmorphing.js#7]
It would be great for new users looking to use this plugin to have instructions on how to install it. This was the first SVG.js plugin I looked at and it took a bit of investigation (looking at the source code and the other plugin documentation) to figure it out. Maybe as a quick fix use the information from one of the other more documented plugins?

**Comment by Fuzzyma** [comment]
I am not sure what the problem is. Can you elaborate what you expect?
Additionally you can change the readme directly in the browser and makt it a PR. That would be awesome!

**Comment by mcshaman** [comment]
Done! #8

**Comment by Fuzzyma** [comment]
Thank you very much!
